#FROM jrottenberg/ffmpeg:4.3-alpine38
FROM golang:latest

#ffmpeg
#RUN apk add --no-cache \
#        ffmpeg \
#        python3 \
#        strace

#youtube-dl
#RUN wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
#RUN chmod a+rx /usr/local/bin/youtube-dl
#
#RUN ln -s /usr/bin/python3 /usr/local/bin/python

WORKDIR /app

COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download
RUN go get github.com/pilu/fresh

COPY ./src .
CMD ["fresh"]